version: "3"
services:
  tasks:
    build: ./tasks
    volumes:
      - ./tasks:/root
      - ./tasks/log:/var/log
    environment:
      - ASANA_ACCESS_TOKEN=${ASANA_ACCESS_TOKEN}
      - ASANA_PROJECT_GID=${ASANA_PROJECT_GID}
      - ASANA_VALUE_FIELD_GID=${ASANA_VALUE_FIELD_GID}
      - ASANA_PARTIAL_COMPLETION_FIELD_GID=${ASANA_PARTIAL_COMPLETION_FIELD_GID}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - REPORT_URL=${REPORT_URL}
      - B2_KEY_ID=${B2_KEY_ID}
      - B2_APPLICATION_KEY=${B2_APPLICATION_KEY}
      - B2_BUCKET_NAME=${B2_BUCKET_NAME}
    networks:
      - postgres
      - browserless
  postgres:
    build: ./postgres
    volumes:
      - ./postgres/.data:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5431:5432
  browserless:
    image: browserless/chrome
    networks:
      - browserless

networks:
  postgres:
  browserless:
